### ISSUE TITLE
Access to Nested JSON Objects

### ISSUE THREAD

**Issue by Celinium** [c-klinger/MMM-JsonValue#2]
Great module. I'm wondering if it's possible to access a nested Json object (i.e. Car1 from the Json below)?

myObj = {
  "name":"John",
  "age":30,
  "cars": {
    "car1":"Ford",
    "car2":"BMW",
    "car3":"Fiat"
  }
 }

Thank you for the answer

Celinium

**Comment by zonorti** [comment]
You need to include it in the jsonPath like `jsonPath: "cars.Car1"`

**Comment by Celinium** [comment]
Excellent. Thank you so much for the reply. It's working fine.  Now I have another similar question, what if the Json contains an array. i.e. :

`{
   "currentWeather":[
      {
         "icon":"clear_skies.png",
         "icontxt":"Clear skies",
         "temp":"-5.7",
         "updateTime":"March 7, 2021 - 14:21"
      }
   ]
}`
I tried several jsonPath syntaxes to extract **icontxt** but I was not able to make it working.  I found an alternate solution which consist to parse and return the first Json element but I'm wondering if there is another native way in NNN-Json module

Celinium

**Comment by zonorti** [comment]
Did not try it with the plugin, but should follow standard jsonPath syntax: `jsonPath: "currentWeather[0].icontxt"`

**Comment by Celinium** [comment]
Hum ... No unfortunately `jsonPath: "currentWeather[0].icontxt"` is not working. The module is in Loading ... state. 
Any idea how to access this Json element?

Celinium

**Comment by c-klinger** [comment]
I think accessing arrays is currently not supported if `jsonPath: "currentWeather[0].icontxt"` is not working. The plugin is using a very simple jsonPath implementation. I will try to add support for this scenario in the next days.

**Comment by c-klinger** [comment]
@Celinium please update the module to latest version. I reworked the implementation and now using dchester/jsonpath npm library. You should be able to do all the stuff mentioned in https://github.com/dchester/jsonpath#jsonpath-syntax including access to array indices :grinning:

To keep config compibility, the leading `$.` is added by the plugin.

**Comment by Celinium** [comment]
Wow ... It's working like a charm! This addition is mega. Thank you so much @c-klinger.
Greetings from Montreal (Canada)
